// Code generated by go-swagger; DO NOT EDIT.

package pokemondescription

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetV1NameHandlerFunc turns a function with the right signature into a get v1 name handler
type GetV1NameHandlerFunc func(GetV1NameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetV1NameHandlerFunc) Handle(params GetV1NameParams) middleware.Responder {
	return fn(params)
}

// GetV1NameHandler interface for that can handle valid get v1 name params
type GetV1NameHandler interface {
	Handle(GetV1NameParams) middleware.Responder
}

// NewGetV1Name creates a new http.Handler for the get v1 name operation
func NewGetV1Name(ctx *middleware.Context, handler GetV1NameHandler) *GetV1Name {
	return &GetV1Name{Context: ctx, Handler: handler}
}

/*GetV1Name swagger:route GET /v1/{name} pokemondescription getV1Name

GetV1Name get v1 name API

*/
type GetV1Name struct {
	Context *middleware.Context
	Handler GetV1NameHandler
}

func (o *GetV1Name) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetV1NameParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
