// Code generated by go-swagger; DO NOT EDIT.

package pokemondescription

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetV1PokemonPokemonNameHandlerFunc turns a function with the right signature into a get v1 pokemon pokemon name handler
type GetV1PokemonPokemonNameHandlerFunc func(GetV1PokemonPokemonNameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetV1PokemonPokemonNameHandlerFunc) Handle(params GetV1PokemonPokemonNameParams) middleware.Responder {
	return fn(params)
}

// GetV1PokemonPokemonNameHandler interface for that can handle valid get v1 pokemon pokemon name params
type GetV1PokemonPokemonNameHandler interface {
	Handle(GetV1PokemonPokemonNameParams) middleware.Responder
}

// NewGetV1PokemonPokemonName creates a new http.Handler for the get v1 pokemon pokemon name operation
func NewGetV1PokemonPokemonName(ctx *middleware.Context, handler GetV1PokemonPokemonNameHandler) *GetV1PokemonPokemonName {
	return &GetV1PokemonPokemonName{Context: ctx, Handler: handler}
}

/*GetV1PokemonPokemonName swagger:route GET /v1/pokemon/{pokemonName} pokemondescription getV1PokemonPokemonName

GetV1PokemonPokemonName get v1 pokemon pokemon name API

*/
type GetV1PokemonPokemonName struct {
	Context *middleware.Context
	Handler GetV1PokemonPokemonNameHandler
}

func (o *GetV1PokemonPokemonName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetV1PokemonPokemonNameParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
