// Code generated by go-swagger; DO NOT EDIT.

package pokemondescription

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetV1PokemonNameHandlerFunc turns a function with the right signature into a get v1 pokemon name handler
type GetV1PokemonNameHandlerFunc func(GetV1PokemonNameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetV1PokemonNameHandlerFunc) Handle(params GetV1PokemonNameParams) middleware.Responder {
	return fn(params)
}

// GetV1PokemonNameHandler interface for that can handle valid get v1 pokemon name params
type GetV1PokemonNameHandler interface {
	Handle(GetV1PokemonNameParams) middleware.Responder
}

// NewGetV1PokemonName creates a new http.Handler for the get v1 pokemon name operation
func NewGetV1PokemonName(ctx *middleware.Context, handler GetV1PokemonNameHandler) *GetV1PokemonName {
	return &GetV1PokemonName{Context: ctx, Handler: handler}
}

/*GetV1PokemonName swagger:route GET /v1/pokemon/{name} pokemondescription getV1PokemonName

GetV1PokemonName get v1 pokemon name API

*/
type GetV1PokemonName struct {
	Context *middleware.Context
	Handler GetV1PokemonNameHandler
}

func (o *GetV1PokemonName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetV1PokemonNameParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
