// Code generated by go-swagger; DO NOT EDIT.

package pokemondescription

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"ozum.safaoglu/pokemon-api/api/swagger/models"
)

// GetPokemonNameOKCode is the HTTP code returned for type GetPokemonNameOK
const GetPokemonNameOKCode int = 200

/*GetPokemonNameOK Describes a pokemon

swagger:response getPokemonNameOK
*/
type GetPokemonNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.Description `json:"body,omitempty"`
}

// NewGetPokemonNameOK creates GetPokemonNameOK with default headers values
func NewGetPokemonNameOK() *GetPokemonNameOK {

	return &GetPokemonNameOK{}
}

// WithPayload adds the payload to the get pokemon name o k response
func (o *GetPokemonNameOK) WithPayload(payload *models.Description) *GetPokemonNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get pokemon name o k response
func (o *GetPokemonNameOK) SetPayload(payload *models.Description) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPokemonNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetPokemonNameDefault generic error response

swagger:response getPokemonNameDefault
*/
type GetPokemonNameDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPokemonNameDefault creates GetPokemonNameDefault with default headers values
func NewGetPokemonNameDefault(code int) *GetPokemonNameDefault {
	if code <= 0 {
		code = 500
	}

	return &GetPokemonNameDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get pokemon name default response
func (o *GetPokemonNameDefault) WithStatusCode(code int) *GetPokemonNameDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get pokemon name default response
func (o *GetPokemonNameDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get pokemon name default response
func (o *GetPokemonNameDefault) WithPayload(payload *models.Error) *GetPokemonNameDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get pokemon name default response
func (o *GetPokemonNameDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPokemonNameDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
