// Code generated by go-swagger; DO NOT EDIT.

package pokemondescription

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetPokemonNameHandlerFunc turns a function with the right signature into a get pokemon name handler
type GetPokemonNameHandlerFunc func(GetPokemonNameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPokemonNameHandlerFunc) Handle(params GetPokemonNameParams) middleware.Responder {
	return fn(params)
}

// GetPokemonNameHandler interface for that can handle valid get pokemon name params
type GetPokemonNameHandler interface {
	Handle(GetPokemonNameParams) middleware.Responder
}

// NewGetPokemonName creates a new http.Handler for the get pokemon name operation
func NewGetPokemonName(ctx *middleware.Context, handler GetPokemonNameHandler) *GetPokemonName {
	return &GetPokemonName{Context: ctx, Handler: handler}
}

/*GetPokemonName swagger:route GET /pokemon/{name} pokemondescription getPokemonName

GetPokemonName get pokemon name API

*/
type GetPokemonName struct {
	Context *middleware.Context
	Handler GetPokemonNameHandler
}

func (o *GetPokemonName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPokemonNameParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
