// Code generated by go-swagger; DO NOT EDIT.

package pokemondescription

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"ozum.safaoglu/pokemon-api/api/swagger/models"
)

// GetV1PokemonNameOKCode is the HTTP code returned for type GetV1PokemonNameOK
const GetV1PokemonNameOKCode int = 200

/*GetV1PokemonNameOK Describes a pokemon

swagger:response getV1PokemonNameOK
*/
type GetV1PokemonNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.Description `json:"body,omitempty"`
}

// NewGetV1PokemonNameOK creates GetV1PokemonNameOK with default headers values
func NewGetV1PokemonNameOK() *GetV1PokemonNameOK {

	return &GetV1PokemonNameOK{}
}

// WithPayload adds the payload to the get v1 pokemon name o k response
func (o *GetV1PokemonNameOK) WithPayload(payload *models.Description) *GetV1PokemonNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 pokemon name o k response
func (o *GetV1PokemonNameOK) SetPayload(payload *models.Description) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1PokemonNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetV1PokemonNameDefault generic error response

swagger:response getV1PokemonNameDefault
*/
type GetV1PokemonNameDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetV1PokemonNameDefault creates GetV1PokemonNameDefault with default headers values
func NewGetV1PokemonNameDefault(code int) *GetV1PokemonNameDefault {
	if code <= 0 {
		code = 500
	}

	return &GetV1PokemonNameDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get v1 pokemon name default response
func (o *GetV1PokemonNameDefault) WithStatusCode(code int) *GetV1PokemonNameDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get v1 pokemon name default response
func (o *GetV1PokemonNameDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get v1 pokemon name default response
func (o *GetV1PokemonNameDefault) WithPayload(payload *models.Error) *GetV1PokemonNameDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 pokemon name default response
func (o *GetV1PokemonNameDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1PokemonNameDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
