// Code generated by mockery v2.3.0. DO NOT EDIT.

package pokemondescription

import (
	middleware "github.com/go-openapi/runtime/middleware"
	mock "github.com/stretchr/testify/mock"
)

// MockGetV1NameHandlerFunc is an autogenerated mock type for the GetV1NameHandlerFunc type
type MockGetV1NameHandlerFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockGetV1NameHandlerFunc) Execute(_a0 GetV1NameParams) middleware.Responder {
	ret := _m.Called(_a0)

	var r0 middleware.Responder
	if rf, ok := ret.Get(0).(func(GetV1NameParams) middleware.Responder); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(middleware.Responder)
		}
	}

	return r0
}
