consumes:
- application/json
info:
  description: Pokemon shakespeare api
  title: A pokemon api
  version: 1.0.0
paths: {}
produces:
- application/json
schemes:
- http
swagger: "2.0"
definitions:
  description:
    $ref: "modelsdefinitions/description.yml#/Description"
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
paths:
  /pokemon/{name}:
    parameters:
      - type: string
        name: name
        in: path
        required: true
    get:
      tags:
        - pokemondescription
      responses:
        200:
          description: Describes a pokemon
          schema:
            $ref: "#/definitions/description"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"