// Code generated by mockery v2.3.0. DO NOT EDIT.

package shakespeare

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSPClient is an autogenerated mock type for the SPClient type
type MockSPClient struct {
	mock.Mock
}

// Translate provides a mock function with given fields: _a0, _a1
func (_m *MockSPClient) Translate(_a0 context.Context, _a1 string) (*Translation, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *Translation
	if rf, ok := ret.Get(0).(func(context.Context, string) *Translation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Translation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
