// Code generated by go-swagger; DO NOT EDIT.

package pokemons

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"ozum.safaoglu/pokemon-api/api/swagger/models"
)

// GetV1PokemonOKCode is the HTTP code returned for type GetV1PokemonOK
const GetV1PokemonOKCode int = 200

/*GetV1PokemonOK List of pokemons

swagger:response getV1PokemonOK
*/
type GetV1PokemonOK struct {

	/*
	  In: Body
	*/
	Payload *models.Pokemons `json:"body,omitempty"`
}

// NewGetV1PokemonOK creates GetV1PokemonOK with default headers values
func NewGetV1PokemonOK() *GetV1PokemonOK {

	return &GetV1PokemonOK{}
}

// WithPayload adds the payload to the get v1 pokemon o k response
func (o *GetV1PokemonOK) WithPayload(payload *models.Pokemons) *GetV1PokemonOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 pokemon o k response
func (o *GetV1PokemonOK) SetPayload(payload *models.Pokemons) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1PokemonOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetV1PokemonDefault generic error response

swagger:response getV1PokemonDefault
*/
type GetV1PokemonDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetV1PokemonDefault creates GetV1PokemonDefault with default headers values
func NewGetV1PokemonDefault(code int) *GetV1PokemonDefault {
	if code <= 0 {
		code = 500
	}

	return &GetV1PokemonDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get v1 pokemon default response
func (o *GetV1PokemonDefault) WithStatusCode(code int) *GetV1PokemonDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get v1 pokemon default response
func (o *GetV1PokemonDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get v1 pokemon default response
func (o *GetV1PokemonDefault) WithPayload(payload *models.Error) *GetV1PokemonDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 pokemon default response
func (o *GetV1PokemonDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1PokemonDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
