// Code generated by mockery v2.3.0. DO NOT EDIT.

package pokemons

import (
	middleware "github.com/go-openapi/runtime/middleware"
	mock "github.com/stretchr/testify/mock"
)

// MockGetHandler is an autogenerated mock type for the GetHandler type
type MockGetHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: _a0
func (_m *MockGetHandler) Handle(_a0 GetParams) middleware.Responder {
	ret := _m.Called(_a0)

	var r0 middleware.Responder
	if rf, ok := ret.Get(0).(func(GetParams) middleware.Responder); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(middleware.Responder)
		}
	}

	return r0
}
